name: pytest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:


jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Setup python
        uses: astral-sh/setup-uv@v7
        with:
          python-version: 3.11
          enable-cache: "auto"

      - name: Create venv and install dependencies
        run: |
          uv venv
          uv pip install -e ".[dev,nixtlaverse]"

      - name: Run tests
        run: uv run pytest
